version: '3'
 
services:
    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: ladtema
        ports: [5432]